version: "2"

services:
  revealjs:
    build: .
    volumes:
      - "./data:/reveal.js/data"
      - "./docs:/reveal.js/build"
    ports:
      - "8000:8000"
      - "35729:35729"
    network_mode: host